2015-12-13 21:50:35,296 - __main__ - INFO - adding resource: /Spot
2015-12-13 21:50:35,296 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2015-12-13 21:50:35,298 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2015-12-13 21:50:41,029 - resources.spot - DEBUG - get(self): invoked
2015-12-13 21:50:41,029 - resources.spot - DEBUG - get(self): invoked
2015-12-13 21:50:41,030 - werkzeug - INFO - 127.0.0.1 - - [13/Dec/2015 21:50:41] "GET /Spot HTTP/1.1" 200 -
2016-01-27 22:59:36,054 - __main__ - INFO - adding resource: /Spot
2016-01-27 22:59:36,055 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-01-27 22:59:36,058 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:13:34,221 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:16:56,657 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:16:56,658 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:16:56,661 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:17:26,073 - resources.spot - DEBUG - get(self): invoked
2016-03-02 00:17:26,073 - resources.spot - DEBUG - get(self): invoked
2016-03-02 00:17:26,074 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:17:26] "GET /Spot HTTP/1.1" 200 -
2016-03-02 00:24:06,964 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:26:29,557 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:26:29,558 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:26:29,559 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:26:40,444 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 174, in wrapper
    @wraps(fn)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'Spot' object has no attribute '__name__'
2016-03-02 00:26:40,447 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:26:40] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:39,785 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:32:39,785 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:32:39,787 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:32:44,483 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:44,484 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:44] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:45,559 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:45,560 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:45] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:46,254 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:46,254 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:46] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:46,740 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:46,740 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:46] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:46,944 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:46,945 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:46] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:32:47,161 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token
2016-03-02 00:32:47,161 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:32:47] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:35:28,078 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:35:28,079 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:35:28,080 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:35:31,150 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:35:31] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:35:31,152 - werkzeug - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/app.py", line 10, in error_router
    if type(e) is JWTError:
NameError: global name 'JWTError' is not defined
2016-03-02 00:37:25,701 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:37:25,701 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:37:25,702 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:37:29,323 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:37:29] "GET /Spot HTTP/1.1" 401 -
2016-03-02 00:39:35,278 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 158, in _jwt_required
    payload = _jwt.jwt_decode_callback(token)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 91, in _default_jwt_decode_handler
    return jwt.decode(token, secret, options=options, algorithms=[algorithm], leeway=leeway)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 175, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/algorithms.py", line 116, in prepare_key
    raise TypeError('Expecting a string- or bytes-formatted key.')
TypeError: Expecting a string- or bytes-formatted key.
2016-03-02 00:39:35,281 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:39:35] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:39:38,654 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 158, in _jwt_required
    payload = _jwt.jwt_decode_callback(token)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 91, in _default_jwt_decode_handler
    return jwt.decode(token, secret, options=options, algorithms=[algorithm], leeway=leeway)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 175, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/algorithms.py", line 116, in prepare_key
    raise TypeError('Expecting a string- or bytes-formatted key.')
TypeError: Expecting a string- or bytes-formatted key.
2016-03-02 00:39:38,655 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:39:38] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:39:39,523 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 158, in _jwt_required
    payload = _jwt.jwt_decode_callback(token)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 91, in _default_jwt_decode_handler
    return jwt.decode(token, secret, options=options, algorithms=[algorithm], leeway=leeway)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 175, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/algorithms.py", line 116, in prepare_key
    raise TypeError('Expecting a string- or bytes-formatted key.')
TypeError: Expecting a string- or bytes-formatted key.
2016-03-02 00:39:39,524 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:39:39] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:40:41,752 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:40:41] "GET /Spot HTTP/1.1" 401 -
2016-03-02 00:41:23,497 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 158, in _jwt_required
    payload = _jwt.jwt_decode_callback(token)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 91, in _default_jwt_decode_handler
    return jwt.decode(token, secret, options=options, algorithms=[algorithm], leeway=leeway)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/api_jws.py", line 175, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/jwt/algorithms.py", line 116, in prepare_key
    raise TypeError('Expecting a string- or bytes-formatted key.')
TypeError: Expecting a string- or bytes-formatted key.
2016-03-02 00:41:23,497 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:41:23] "GET /Spot HTTP/1.1" 500 -
2016-03-02 00:44:29,677 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:44:29,677 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:44:29,679 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:44:33,320 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:44:33] "GET /Spot HTTP/1.1" 401 -
2016-03-02 00:50:23,886 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:50:23] "GET /Spot HTTP/1.1" 401 -
2016-03-02 00:50:30,203 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:50:30] "GET /Spot HTTP/1.1" 401 -
2016-03-02 00:52:49,541 - __main__ - INFO - adding resource: /Spot
2016-03-02 00:52:49,543 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 00:52:49,546 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 00:52:58,371 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 00:52:58] "GET /Spot HTTP/1.1" 401 -
2016-03-02 21:40:19,439 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 21:40:19] "GET /Spot HTTP/1.1" 401 -
2016-03-02 21:40:20,488 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 21:40:20] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:23:22,074 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:23:22] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:36:14,411 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:36:14] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:10,980 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:10] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:12,623 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:12] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:13,555 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:13] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:14,022 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:14] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:14,275 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:14] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:14,483 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:14] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:39:14,663 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:39:14] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:40:04,800 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:40:04] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:40:05,965 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:40:05] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:41:41,571 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:41:41] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:41:54,151 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:41:54] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:41:54,958 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:41:54] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:42:32,584 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:42:32] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:46:51,355 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:46:51] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:48:09,555 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:48:09] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:48:30,887 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
TypeError: identity() takes exactly 1 argument (2 given)
2016-03-02 22:48:30,895 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:48:30] "GET /Spot HTTP/1.1" 500 -
2016-03-02 22:54:03,698 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:54:03] "GET /Spot HTTP/1.1" 401 -
2016-03-02 22:54:07,783 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
TypeError: identity() takes exactly 1 argument (2 given)
2016-03-02 22:54:07,784 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 22:54:07] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:01:04,005 - __main__ - INFO - adding resource: /Spot
2016-03-02 23:01:04,006 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 23:01:04,009 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 23:01:29,412 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 15, in identity
    bt_user_id = payload['btUserId']
AttributeError: TokenValidator instance has no attribute '__getitem__'
2016-03-02 23:01:29,417 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:01:29] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:01:30,267 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 15, in identity
    bt_user_id = payload['btUserId']
AttributeError: TokenValidator instance has no attribute '__getitem__'
2016-03-02 23:01:30,268 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:01:30] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:01:31,855 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 15, in identity
    bt_user_id = payload['btUserId']
AttributeError: TokenValidator instance has no attribute '__getitem__'
2016-03-02 23:01:31,856 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:01:31] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:01:32,539 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 15, in identity
    bt_user_id = payload['btUserId']
AttributeError: TokenValidator instance has no attribute '__getitem__'
2016-03-02 23:01:32,540 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:01:32] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:03:43,258 - __main__ - INFO - adding resource: /Spot
2016-03-02 23:03:43,259 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 23:03:43,262 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 23:03:48,461 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 15, in identity
    print 'payload: ' + payload
TypeError: cannot concatenate 'str' and 'instance' objects
2016-03-02 23:03:48,462 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:03:48] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:04:17,320 - __main__ - INFO - adding resource: /Spot
2016-03-02 23:04:17,320 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 23:04:17,321 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 23:04:20,028 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 17, in identity
    bt_user_id = payload['btUserId']
AttributeError: TokenValidator instance has no attribute '__getitem__'
2016-03-02 23:04:20,030 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:04:20] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:05:03,836 - __main__ - INFO - adding resource: /Spot
2016-03-02 23:05:03,837 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 23:05:03,838 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 23:05:08,493 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 16, in identity
    print 'a: ' + str(a)
NameError: global name 'a' is not defined
2016-03-02 23:05:08,494 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:05:08] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:05:10,787 - __main__ - ERROR - Internal Error
Traceback (most recent call last):
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/Users/jacekdalkowski/anaconda/envs/biketimer-webapi/lib/python2.7/site-packages/flask_jwt/__init__.py", line 162, in _jwt_required
    _request_ctx_stack.top.current_identity = identity = _jwt.identity_callback(payload)
  File "/Users/jacekdalkowski/Dev/bike_timer/web-api/biketimerwebapi/security/token_validator.py", line 16, in identity
    print 'a: ' + str(a)
NameError: global name 'a' is not defined
2016-03-02 23:05:10,788 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:05:10] "GET /Spot HTTP/1.1" 500 -
2016-03-02 23:05:30,332 - __main__ - INFO - adding resource: /Spot
2016-03-02 23:05:30,333 - __main__ - INFO - starting app on host: 0.0.0.0:5001
2016-03-02 23:05:30,334 - werkzeug - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2016-03-02 23:05:41,605 - resources.spot - DEBUG - get(self): invoked
2016-03-02 23:05:41,605 - resources.spot - DEBUG - get(self): invoked
2016-03-02 23:05:41,606 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:05:41] "GET /Spot HTTP/1.1" 200 -
2016-03-02 23:07:35,181 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:07:35] "GET /Spot HTTP/1.1" 401 -
2016-03-02 23:07:52,958 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:07:52] "GET /Spot HTTP/1.1" 401 -
2016-03-02 23:08:02,468 - resources.spot - DEBUG - get(self): invoked
2016-03-02 23:08:02,468 - resources.spot - DEBUG - get(self): invoked
2016-03-02 23:08:02,468 - werkzeug - INFO - 127.0.0.1 - - [02/Mar/2016 23:08:02] "GET /Spot HTTP/1.1" 200 -
